/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figuras;
import figuras.Figuras;
import figuras.Cuadrado;
import figuras.Triangulo;
import figuras.Circulo;

/**
 *
 * @author odraude
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    final float PI=(float) 3.1416;
    float base,altura,radio,area;
    public Ventana() {
        initComponents();
        esconderCampos();
    }
    public void esconderCampos(){
        txtBase.hide();
        txtAltura.hide();
        txtBase2.hide();
        txtAltura2.hide();
        txtRadio.hide();
        btnOk.hide();
        btnOk2.hide();
        btnOk3.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCuadrado = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        BtnCirculo = new javax.swing.JButton();
        txtBase = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtBase2 = new javax.swing.JTextField();
        txtAltura2 = new javax.swing.JTextField();
        txtRadio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPnlVentana = new javax.swing.JTextPane();
        btnOk = new javax.swing.JButton();
        btnOk2 = new javax.swing.JButton();
        btnOk3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnCuadrado.setText("Cuadrado");
        btnCuadrado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuadradoMouseClicked(evt);
            }
        });
        getContentPane().add(btnCuadrado);
        btnCuadrado.setBounds(10, 20, 110, 19);

        btnTriangulo.setText("Triangulo");
        btnTriangulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTriangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrianguloMouseClicked(evt);
            }
        });
        getContentPane().add(btnTriangulo);
        btnTriangulo.setBounds(130, 20, 130, 19);

        BtnCirculo.setText("Circulo");
        BtnCirculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCirculoMouseClicked(evt);
            }
        });
        getContentPane().add(BtnCirculo);
        BtnCirculo.setBounds(270, 20, 120, 19);

        txtBase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBase.setText("Base");
        getContentPane().add(txtBase);
        txtBase.setBounds(10, 60, 110, 30);

        txtAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAltura.setText("Altura");
        getContentPane().add(txtAltura);
        txtAltura.setBounds(10, 110, 110, 30);

        txtBase2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBase2.setText("Base");
        getContentPane().add(txtBase2);
        txtBase2.setBounds(130, 60, 110, 30);

        txtAltura2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAltura2.setText("Altura");
        getContentPane().add(txtAltura2);
        txtAltura2.setBounds(130, 110, 110, 30);

        txtRadio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRadio.setText("Radio");
        getContentPane().add(txtRadio);
        txtRadio.setBounds(270, 60, 120, 30);

        txtPnlVentana.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(txtPnlVentana);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 360, 120);

        btnOk.setText("OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(20, 150, 54, 25);

        btnOk2.setText("OK");
        btnOk2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOk2MouseClicked(evt);
            }
        });
        getContentPane().add(btnOk2);
        btnOk2.setBounds(140, 150, 54, 25);

        btnOk3.setText("OK");
        btnOk3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOk3MouseClicked(evt);
            }
        });
        getContentPane().add(btnOk3);
        btnOk3.setBounds(280, 100, 54, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuadradoMouseClicked
        // TODO add your handling code here:
        txtBase.show(true);
        txtAltura.show(true);
        txtBase2.hide();
        txtAltura2.hide();
        txtRadio.hide();
        btnOk.show(true);
        btnOk2.hide();
        btnOk3.hide();
    }//GEN-LAST:event_btnCuadradoMouseClicked

    private void btnTrianguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrianguloMouseClicked
        // TODO add your handling code here:
        txtBase.hide();
        txtAltura.hide();
        txtBase2.show(true);
        txtAltura2.show(true);
        txtRadio.hide();
        btnOk.hide();
        btnOk2.show(true);
        btnOk3.hide();
    }//GEN-LAST:event_btnTrianguloMouseClicked

    private void BtnCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCirculoMouseClicked
        // TODO add your handling code here:
        txtBase.hide();
        txtAltura.hide();
        txtBase2.hide();
        txtAltura2.hide();
        txtRadio.show(true);
        btnOk.hide();
        btnOk2.hide();
        btnOk3.show(true);
    }//GEN-LAST:event_BtnCirculoMouseClicked

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        // TODO add your handling code here:
        base=Float.parseFloat(txtBase.getText());
        altura=Float.parseFloat(txtAltura.getText());
        Figuras cuadrado= new Cuadrado(base,altura);
        area=cuadrado.getArea();
        txtPnlVentana.setText("El area del cuadrado es de:"+area);
    }//GEN-LAST:event_btnOkMouseClicked

    private void btnOk2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOk2MouseClicked
        // TODO add your handling code here:
        base=Float.parseFloat(txtBase2.getText());
        altura=Float.parseFloat(txtAltura2.getText());
        Figuras triangulo= new Triangulo(base,altura);
        area=triangulo.getArea();
        txtPnlVentana.setText("El area del triangulo es de:"+area);
    }//GEN-LAST:event_btnOk2MouseClicked

    private void btnOk3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOk3MouseClicked
        // TODO add your handling code here:
        radio=Float.parseFloat(txtRadio.getText());
        Figuras circulo= new Circulo(PI,radio);
        area=circulo.getArea();
        txtPnlVentana.setText("El area del circulo es de:"+area);
    }//GEN-LAST:event_btnOk3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCirculo;
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnOk2;
    private javax.swing.JButton btnOk3;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAltura2;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtBase2;
    private javax.swing.JTextPane txtPnlVentana;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
